import React from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowRight, FlaskConical, Library, Search } from 'lucide-react';
import { BRAND_DESCRIPTION, BRAND_NAME, BRAND_TAGLINE } from '../data/branding';
import { COURSES } from '../data/courseCatalog';
import { searchLearningDestinations } from '../data/learningCatalog';
import { AppDestination } from '../types';
import { MathCsState } from '../utils/mathCsStorage';
import { getCourseProgress, getRecommendedTopic } from '../utils/progress';
import { CourseCard } from '../components/course/CourseCard';

interface DashboardProps { state: MathCsState; onNavigate: (destination: AppDestination) => void; }
export const DashboardView: React.FC<DashboardProps> = ({ state, onNavigate }) => {
  const reduce = useReducedMotion(); const [query, setQuery] = React.useState(''); const results = searchLearningDestinations(query);
  return <motion.div initial={false} animate={{ opacity: 1, y: 0 }} className="mx-auto max-w-6xl"><header className="mb-8"><p className="text-xs font-bold uppercase tracking-[0.22em] text-cyan-300">{BRAND_TAGLINE}</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-white md:text-6xl">{BRAND_NAME}</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-300">{BRAND_DESCRIPTION}</p></header><div className="relative mb-8"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={18} /><label className="sr-only" htmlFor="course-search">Search course topics</label><input id="course-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search limits, matrices, eigenvalues…" className="focus-ring h-13 w-full rounded-xl border border-white/10 bg-[#0b1726]/90 pl-11 pr-4 text-white placeholder:text-slate-500" />{query && <div className="absolute z-20 mt-2 w-full rounded-xl border border-white/10 bg-[#0b1726] p-2 shadow-2xl">{results.length ? results.map((result) => <button key={result.topic.id} className="focus-ring flex w-full items-center justify-between rounded-lg p-3 text-left hover:bg-white/5" onClick={() => onNavigate(result.destination)}><span><span className="block font-semibold text-white">{result.topic.title}</span><span className="text-xs text-slate-500">{result.course.shortTitle}</span></span><ArrowRight size={16} /></button>) : <p className="p-3 text-sm text-slate-400">No matching topic</p>}</div>}</div><section className="grid gap-5 md:grid-cols-2" aria-label="Courses">{COURSES.map((course) => { const quizzes = state.quizResults.filter((result) => result.courseId === course.id); return <CourseCard key={course.id} course={course} progress={getCourseProgress(state, course)} completedCount={course.topics.filter((topic) => state.completedTopicIds.includes(topic.id)).length} recommendedTopic={getRecommendedTopic(state, course)} latestQuiz={quizzes.at(-1)} onNavigate={onNavigate} />; })}</section><section className="mt-7 grid gap-4 sm:grid-cols-2"><button className="focus-ring notebook-panel flex items-center gap-4 p-5 text-left" onClick={() => onNavigate({ section: 'math-lab' })}><span className="rounded-xl bg-cyan-300/10 p-3 text-cyan-200"><FlaskConical /></span><span><span className="block font-semibold text-white">Math Lab</span><span className="mt-1 block text-sm text-slate-400">Explore approved function, matrix, and vector presets.</span></span></button><button className="focus-ring notebook-panel flex items-center gap-4 p-5 text-left" onClick={() => onNavigate({ section: 'formulas' })}><span className="rounded-xl bg-amber-300/10 p-3 text-amber-200"><Library /></span><span><span className="block font-semibold text-white">Formula Workspace</span><span className="mt-1 block text-sm text-slate-400">Keep formulas and your local notes together.</span></span></button></section></motion.div>;
};
