import React, { useMemo, useState } from 'react';
import { getDeterminant, getInverse, multiplyMatrices } from '../../utils/matrixMath';
type Matrix = number[][];
const parse = (text: string): { ok: true; value: Matrix } | { ok: false; error: string } => { const rows = text.trim().split(/\n+/).map((row) => row.trim().split(/[ ,]+/).map(Number)); if (!text.trim()) return { ok:false,error:'Enter at least one row' }; if (rows.some((row) => row.some((value) => !Number.isFinite(value)))) return { ok:false,error:'Use finite numerical entries' }; if (new Set(rows.map((row) => row.length)).size !== 1) return { ok:false,error:'All rows must have the same length' }; return { ok:true,value:rows }; };
export const MatrixLab: React.FC = () => {
  const [a,setA]=useState('1 2\n3 4'); const [b,setB]=useState('1 0\n0 1'); const [operation,setOperation]=useState<'determinant'|'inverse'|'multiply'>('determinant');
  const result = useMemo(() => { const A=parse(a); if(A.ok === false)return A.error; if(operation==='determinant'){const value=getDeterminant(A.value);return value===null?'This operation requires a square matrix':`det(A) = ${value}`;} if(operation==='inverse'){const value=getInverse(A.value);return value?`A⁻¹ = ${JSON.stringify(value.map((row)=>row.map((x)=>Math.round(x*1000)/1000)))}`:'A singular matrix has no inverse';} const B=parse(b); if(B.ok === false)return B.error; const value=multiplyMatrices(A.value,B.value);return value?`AB = ${JSON.stringify(value)}`:'Columns of A must equal rows of B'; },[a,b,operation]);
  return <section className="grid gap-5 xl:grid-cols-[320px_minmax(0,1fr)]"><div className="notebook-panel p-5"><h2 className="text-xl font-bold text-white">Matrix Lab</h2><label className="mt-4 block text-sm text-slate-300">Operation<select value={operation} onChange={(event)=>setOperation(event.target.value as typeof operation)} className="focus-ring mt-2 w-full rounded-lg border border-white/10 bg-slate-950 p-2"><option value="determinant">Determinant</option><option value="inverse">Inverse</option><option value="multiply">Multiply A×B</option></select></label><label className="mt-4 block text-sm text-slate-300">Matrix A<textarea value={a} onChange={(event)=>setA(event.target.value)} rows={4} className="focus-ring mt-2 w-full rounded-lg border border-white/10 bg-slate-950 p-3 font-mono" /></label>{operation==='multiply'&&<label className="mt-4 block text-sm text-slate-300">Matrix B<textarea value={b} onChange={(event)=>setB(event.target.value)} rows={4} className="focus-ring mt-2 w-full rounded-lg border border-white/10 bg-slate-950 p-3 font-mono" /></label>}</div><div className="notebook-panel p-5"><h3 className="font-semibold text-white">Deterministic result</h3><p className="formula-panel mt-4 break-words font-mono text-cyan-100" role="status">{result}</p><div className="mt-5 text-sm leading-7 text-slate-300"><p>Rows are entered on separate lines; values use spaces or commas.</p><p className="mt-2">Determinants describe oriented scale, inverses undo transformations, and products compose transformations.</p></div></div></section>;
};
