import React, { useState } from 'react';
import { addVectors, applyMatrix2, dot, lineFromPointDirection, magnitude, Vector2 } from '../../utils/vectorMath';
export const VectorGeometryLab: React.FC = () => {
  const [u,setU] = useState<Vector2>([2,1]); const [v,setV] = useState<Vector2>([1,3]); const [mode,setMode] = useState<'vectors'|'transformations'|'lines'>('vectors');
  const setCoordinate = (setter: React.Dispatch<React.SetStateAction<Vector2>>, vector: Vector2, index: number, value: number) => setter(index === 0 ? [value,vector[1]] : [vector[0],value]);
  const interpretation = mode === 'vectors' ? `u+v=${JSON.stringify(addVectors(u,v).ok ? (addVectors(u,v) as {ok:true;value:number[]}).value : [])}; u·v=${dot(u,v).ok ? (dot(u,v) as {ok:true;value:number}).value : 'error'}; |u|=${magnitude(u).ok ? (magnitude(u) as {ok:true;value:number}).value.toFixed(2) : 'error'}` : mode === 'transformations' ? `90° rotation maps u to ${JSON.stringify((applyMatrix2([[0,-1],[1,0]],u) as {ok:true;value:Vector2}).value)}` : (lineFromPointDirection(u,v).ok ? (lineFromPointDirection(u,v) as {ok:true;value:string}).value : 'Choose a nonzero direction');
  const arrow = (vector: Vector2, className: string) => <line x1="200" y1="200" x2={200+vector[0]*45} y2={200-vector[1]*45} className={className} stroke="currentColor" strokeWidth="4" markerEnd="url(#arrow)" />;
  return <section className="grid gap-5 xl:grid-cols-[300px_minmax(0,1fr)]"><div className="notebook-panel p-5"><h2 className="text-xl font-bold text-white">Vector & Geometry Lab</h2><div className="mt-4 grid grid-cols-3 gap-2">{(['vectors','transformations','lines'] as const).map((item) => <button key={item} className={`focus-ring rounded-lg px-2 py-2 text-xs capitalize ${mode===item?'bg-cyan-300 text-slate-950':'border border-white/10'}`} onClick={() => setMode(item)}>{item}</button>)}</div>{[[u,setU,'u'],[v,setV,'v']].map(([vector,setter,label]) => <fieldset key={label as string} className="mt-5"><legend className="font-semibold text-white">Vector {label as string}</legend><div className="mt-2 grid grid-cols-2 gap-2">{[0,1].map((index) => <label key={index} className="text-xs text-slate-400">{index?'y':'x'}<input type="number" className="focus-ring mt-1 w-full rounded-lg border border-white/10 bg-slate-950 p-2 text-white" value={(vector as Vector2)[index]} onChange={(event) => setCoordinate(setter as React.Dispatch<React.SetStateAction<Vector2>>, vector as Vector2, index, Number(event.target.value))} /></label>)}</div></fieldset>)}</div><div className="notebook-panel p-4"><svg viewBox="0 0 400 400" className="mx-auto w-full max-w-xl" role="img" aria-label="Coordinate plane showing vectors u and v"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="5" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3 z" fill="currentColor" /></marker></defs><rect width="400" height="400" fill="#07111f" /><path d="M0 200H400M200 0V400" stroke="rgba(148,163,184,.35)" />{arrow(u,'text-cyan-300')}{arrow(v,'text-amber-300')}</svg><p className="formula-panel mt-4 text-sm text-slate-200" aria-live="polite">{interpretation}</p><p className="mt-2 text-xs text-slate-500">Cyan arrow: u. Amber arrow: v. The text panel carries the complete result.</p></div></section>;
};
